### PR TITLE
xorgproto: new formula

### PR DESCRIPTION
**Pull request by maxim-belkin**
New formula that will replace a bunch of other `proto` packages.

### CODE REVIEW

**Comment by sjackman** [comment]
Woohoo! That's great! We'll have to test the transition for the old many-packages-system to the new system so that all the old `*proto` packages get unlinked and replaced by `xorgproto` by `brew update && brew upgrade`.

**Comment by sjackman** [comment]
I don't know myself how to handle those migrations. Could you please research it?

**Comment by maxim-belkin** [comment]
Hmm... Those are just `proto` packages, so nothing should change except for dependency definitions in formulae. Or am I missing something?

**Comment by sjackman** [comment]
I'm guessing that `xorgproto` installs files that have the same name and conflict with the old `*proto` formulae. When the user runs `brew upgrade`, it'll install `xorgproto`, and attempt to link it, and fail due to the conflicts. `brew update && brew upgrade` needs to unlink all the old `*proto` packages for the user.

**Comment by maxim-belkin** [comment]
ah, that's right... Time to 🤔

**Comment by sjackman** [comment]
I believe there's some kind of support in Homebrew/brew for this sort of case, though I've never used it. It might have the name "migrate" something or other.

**Pull request merged**
