### PR TITLE
Remove unnecessary livecheck blocks

### PR DESCRIPTION
**Pull request by maxim-belkin**
per your suggestion, @samford, removing livecheck blocks from libdmx and libpciaccess

### CODE REVIEW

**Comment by samford** [comment]
The updated `Xorg` strategy that I'm working on in Homebrew/homebrew-livecheck#1150 allows us to remove `livecheck` blocks from all of the following formulae:

* libdmx
* libfontenc
* libfs
* libice
* libpciaccess
* libpthread-stubs
* libsm
* libx11
* libxau
* libxaw
* libxcb
* libxcomposite
* libxcursor
* libxdamage
* libxdmcp
* libxext
* libxfixes
* libxfont
* libxfont2
* libxfontcache
* libxft
* libxi
* libxinerama
* libxkbfile
* libxmu
* libxpm
* libxrandr
* libxrender
* libxres
* libxscrnsaver
* libxshmfence
* libxt
* libxtst
* libxv
* libxvmc
* xtrans

I would probably wait until the aforementioned PR is merged and I've removed the `Xorg` strategy here before merging this PR (so all these checks will work). I'm working on wrapping up work on the `Xorg` strategy, so I'll merge it sometime today.

**Comment by maxim-belkin** [comment]
Failure is related to a recent change in GitHub Actions and will be fixed by Homebrew/brew#8009

**Comment by samford** [comment]
Looks good to me. Now that the `Xorg` strategy is incorporated into homebrew-livecheck and it has been removed from this tap, this PR can be merged. I ran a test on this tap's formulae and all the `Xorg` ones work properly after these removals.

There are still a few unrelated formulae that need `livecheck` blocks and I've already worked these out. I'll open PRs for these momentarily. Once they're all merged, all the checks in this tap should be working.

**Comment by maxim-belkin** [comment]
> I'll open PRs for these momentarily. Once they're all merged, all the checks in this tap should be working.

Thanks, Sam!

**Pull request merged**
