### PR TITLE
mesa: change dependency on xorg to :x11

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by ilovezfs** [comment]
@maxim-belkin https://ftp.cc.uoc.gr/mirrors/linux/lfs/LFS/conglomeration/Xorg/mesa-13.0.4-add_xdemos-1.patch

**Comment by maxim-belkin** [comment]
@sjackman shall we merge this one?

**Review by rwhogg — APPROVED** [review]

**Comment by maxim-belkin** [comment]
Thanks, Bob! we can skip updating the bottle, right?

**Comment by bw-yuhogg** [comment]
They're just demos, right? If so, yeah, IMO there's no real need to update the bottle.

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
:shipit:

**Pull request closed without merging**
