### PR TITLE
mesa: strip binaries; move to python 3.8

### PR DESCRIPTION
**Pull request by iMichka**
The size of mesa after installation is around 2.6 Gb,
after striping less than 300M.

### CODE REVIEW

**Comment by iMichka** [comment]
@maxim-belkin just FYI; got some build errors with llvm 10 and I need to rebuild a llvm 9 bottle in homebrew-core, so I went for llvm 8 for the time being.

**Comment by maxim-belkin** [comment]
@iMichka, I cherry-picked your style-fixing commits, so feel free to remove them from your branch... Also, if you need to modify some of the CI steps -- feel free to do that.

**Comment by iMichka** [comment]
Thanks, no issue. I will remove these commits.

We have an issue with dependencies that do not install, I'll have a look if I can fix this:
> 2020-05-18T18:54:56.0768226Z [31mError:[0m No such file or directory @ rb_sysopen - /github/home/.cache/Homebrew/downloads/40284c34ec231cc6a152c4d5234a03f3ad4427971c80a049c946b8a447c0bd3e--libyaml-0.2.4.x86_64_linux.bottle.tar.gz
2020-05-18T18:57:54.5873973Z [31mError:[0m No such file or directory @ rb_sysopen - /github/home/.cache/Homebrew/downloads/c85ec295b782a957f8118853fbf37c892e451c23335c923e7eb5ed93121596d7--ruby-2.7.1_3.x86_64_linux.bottle.tar.gz

**Comment by iMichka** [comment]
@maxim-belkin this is now ready for review. The build worked on GitHub Actions.

What are the steps to get a bottle uploaded?

**Comment by iMichka** [comment]
Superseded by #639

**Pull request closed without merging**
