### PR TITLE
xdpyinfo: Add a test

### PR DESCRIPTION
**Pull request by rwhogg**
Also delete some commented-out code

# Contributing to homebrew-xorg:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [x] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
Travis failed:

```
$ brew audit -D --except=revision_and_version_scheme --strict $(cd $(brew --repo linuxbrew/xorg)/Formula; ls *.rb | sed 's|.rb$||') || true
linuxbrew/xorg/libevdev:
  * Dependency 'python' from homebrew/core is an alias; use the canonical name 'python@3.8'.
linuxbrew/xorg/libxcb:
  * Dependency 'python' from homebrew/core is an alias; use the canonical name 'python@3.8'.
linuxbrew/xorg/xcb-proto:
  * Dependency 'python' from homebrew/core is an alias; use the canonical name 'python@3.8'.
```

I'll admit that I have not kept pace with all the changes to Python that have happened recently - if someone can confirm that we do want `python@3.8` rather than the nonspecific `python` I can make the above changes on a separate PR but at the moment I'm not sure what the proper course of action is.

**Comment by jonchang** [comment]
Yeah, we've moved towards versioning each minor release of Python. Users running `brew install python` will automatically install `python@3.8`, and should automatically upgrade to `python@3.9` when that releases, but formulae depending on `python@3.8` will have more time to migrate to e.g. `python@3.9` without holding up user access to the newer version of Python.

> if someone can confirm that we do want python@3.8 rather than the nonspecific python I can make the above changes on a separate PR but at the moment I'm not sure what the proper course of action is.

This is exactly what we want! If you can spare the time to open the pull request that would be fantastic.

**Comment by bw-yuhogg** [comment]
Thanks for explaining, that makes a lot of sense :+1:

Opened up a :snake: PR at #663

**Review by maxim-belkin — APPROVED** [review]
Tested locally -- works great! Thanks, Bob!

**Pull request merged**
