### PR TITLE
mesa 17.2.3

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by iMichka** [comment]
I just saw that the current version (17.1.6) fails to build from source in our docker container. Let's try to update to the latest version. I did not test this locally so I have no clue if this will build.

**Comment by maxim-belkin** [comment]
```
checking for wayland-scanner... yes
checking for x11-xcb xcb xcb-dri2 >= 1.8 xcb-xfixes... yes
checking for wayland-client >= 1.11 wayland-server >= 1.11... yes
configure: error: wayland-protocols >= 1.8 is needed to compile the wayland platform

==> Formula
Tap: linuxbrew/xorg
```

**Comment by iMichka** [comment]
Woups forgot about this. Lets bump wayland to 1.14, and wayland protocols to 1.11

**Comment by iMichka** [comment]
Will need #333 and #334 first

**Comment by iMichka** [comment]
Travis: `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by iMichka** [comment]
All green :)

**Comment by maxim-belkin** [comment]
why did you add `depends_on "linuxbrew/xorg/wayland-protocols" => :recommended`?

**Comment by iMichka** [comment]
Because I got that error:
> configure: error: wayland-protocols >= 1.8 is needed to compile the wayland platform

And `wayland-protocols` brings in `wayland`

**Pull request closed without merging**
