### PR TITLE
libevdev: Build with python@2

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by sjackman** [comment]
Does `libevdev` fail to build with Python 3? If so, what is the error message?

**Comment by iMichka** [comment]
I did not try it. I just want to rebuild to bottle to clean up the dependency tree; we can experiment with python3 later :)

**Comment by sjackman** [comment]
I'd rather go with Python 3 if it works. Your call though.

**Comment by iMichka** [comment]
```
linuxbrew/xorg/libevdev:
  * Dependency 'python@2' is an alias; use the canonical name 'python'.
```

**Comment by iMichka** [comment]
Let's try just with a rebuild then, which will use python3. But the python3 bottle does not exist at this moment ...

**Comment by iMichka** [comment]
```
==> Installing linuxbrew/xorg/libevdev dependency: python
==> Downloading https://linuxbrew.bintray.com/bottles/python-2.7.14_5.x86_64_linux.bottle.tar.gz
Already downloaded: /home/linuxbrew/.cache/Homebrew/python-2.7.14_5.x86_64_linux.bottle.tar.gz
```
https://circleci.com/gh/Linuxbrew/homebrew-xorg/992
@sjackman @maxim-belkin This sounds weird. It should be installing Python 3.

**Comment by sjackman** [comment]
```
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 8c3ca23d255a2f734f8257c90ccabcbbb3fec3d8
Core tap last commit: 4 days ago
```
and `HOMEBREW_NO_AUTO_UPDATE=1` is set.
https://circleci.com/gh/Linuxbrew/homebrew-xorg/992
@maxim-belkin `.circleci/config.yml` needs to `brew update`

**Comment by sjackman** [comment]
I'm confused about that. I thought that `brew test-bot` would update Homebrew/core. It does not appear to though. That may be the default `brew test-bot` behaviour on CircleCI. The behaviour may be different on TravisCI or Jenkins.

**Comment by maxim-belkin** [comment]
> @maxim-belkin .circleci/config.yml needs to brew update

#354 
I'm also disabling analytics in #355

**Comment by iMichka** [comment]
Rebasing. Thanks for finding this out!

**Review by maxim-belkin — APPROVED** [review]
Thanks so much for your contribution! Without people like you submitting PRs we couldn't run this project. You rock, @iMichka 

:trollface:

**Comment by iMichka** [comment]
@maxim-belkin :) 

I went for `python@2`, I need to break that dependency circle. We can think about python 3 here later.

**Comment by sjackman** [comment]
😆

**Pull request closed without merging**
