### PR TITLE
Mesa: build i965 dri drivers

### PR DESCRIPTION
**Pull request by rwhogg**
# Contributing to homebrew-xorg:
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [x] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

Here's the failure from `git-cola`:

```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
```

### CODE REVIEW

**Review by maxim-belkin — APPROVED** [review]

**Comment by bw-yuhogg** [comment]
Timed out trying to build `llvm` 😦

**Comment by bw-yuhogg** [comment]
Circle CI ran out out of memory.

**Comment by bw-yuhogg** [comment]
Test failed on Travis:

```
Testing linuxbrew/xorg/mesa

==> ldd /home/linuxbrew/.linuxbrew/Cellar/mesa/17.0.0_1/lib/libGL.so

Error: linuxbrew/xorg/mesa: failed

Expected /libxcb\-randr\.so\.0/ to match "\tlinux-vdso.so.1 =>  (0x00007ffe84fdf000)\n\tlibexpat.so.1 => /home/linuxbrew/.linuxbrew/lib/libexpat.so.1 (0x00007f85a0f54000)\n\tlibxcb-dri3.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-dri3.so.0 (0x00007f85a0d50000)\n\tlibxcb-present.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-present.so.0 (0x00007f85a0b49000)\n\tlibxcb-sync.so.1 => /home/linuxbrew/.linuxbrew/lib/libxcb-sync.so.1 (0x00007f85a0940000)\n\tlibxshmfence.so.1 => /home/linuxbrew/.linuxbrew/lib/libxshmfence.so.1 (0x00007f85a073d000)\n\tlibglapi.so.0 => /home/linuxbrew/.linuxbrew/opt/mesa/lib/libglapi.so.0 (0x00007f85a0509000)\n\tlibXext.so.6 => /home/linuxbrew/.linuxbrew/lib/libXext.so.6 (0x00007f85a02f8000)\n\tlibXdamage.so.1 => /home/linuxbrew/.linuxbrew/lib/libXdamage.so.1 (0x00007f85a00f4000)\n\tlibXfixes.so.3 => /home/linuxbrew/.linuxbrew/lib/libXfixes.so.3 (0x00007f859feec000)\n\tlibX11-xcb.so.1 => /home/linuxbrew/.linuxbrew/lib/libX11-xcb.so.1 (0x00007f859fce9000)\n\tlibX11.so.6 => /home/linuxbrew/.linuxbrew/lib/libX11.so.6 (0x00007f859f9a6000)\n\tlibxcb.so.1 => /home/linuxbrew/.linuxbrew/lib/libxcb.so.1 (0x00007f859f779000)\n\tlibxcb-glx.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-glx.so.0 (0x00007f859f55a000)\n\tlibxcb-dri2.so.0 => /home/linuxbrew/.linuxbrew/lib/libxcb-dri2.so.0 (0x00007f859f353000)\n\tlibXxf86vm.so.1 => /home/linuxbrew/.linuxbrew/lib/libXxf86vm.so.1 (0x00007f859f14c000)\n\tlibdrm.so.2 => /home/linuxbrew/.linuxbrew/lib/libdrm.so.2 (0x00007f859ef38000)\n\tlibm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f859ec24000)\n\tlibpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f859ea05000)\n\tlibdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f859e801000)\n\tlibc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f859e438000)\n\tlibbsd.so.0 => /home/linuxbrew/.linuxbrew/lib/libbsd.so.0 (0x00007f859e224000)\n\tlibXau.so.6 => /home/linuxbrew/.linuxbrew/lib/libXau.so.6 (0x00007f859e01f000)\n\tlibXdmcp.so.6 => /home/linuxbrew/.linuxbrew/lib/libXdmcp.so.6 (0x00007f859de18000)\n\t/lib64/ld-linux-x86-64.so.2 (0x00005577bd6d0000)\n\tlibrt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f859dc0f000)".
```

Circle ran out of memory with 8 threads. Let's try 6.

**Comment by bw-yuhogg** [comment]
6 also used too much memory. Trying 4.

**Comment by bw-yuhogg** [comment]
Again 4, used too much memory. Trying 2.

**Comment by bw-yuhogg** [comment]
Finally resolved this in https://github.com/Linuxbrew/homebrew-xorg/commit/66d2069ab90f2dda5d773ef5c3cb4c5acc6aaed5

**Pull request closed without merging**
