### PR TITLE
libpthread-stubs 0.4

### PR DESCRIPTION
**Pull request by rwhogg**
Signed-off-by: Bob W. Hogg <rwhogg@linux.com>

# Contributing to homebrew-xorg:
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [ ] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by maxim-belkin** [comment]
why do we need to bump up revisions? `libpthread-stubs` is just a plug, no?
```
$ brew list -v libpthread-stubs
/home/linuxbrew/.linuxbrew/Cellar/libpthread-stubs/0.3/lib/pkgconfig/pthread-stubs.pc
/home/linuxbrew/.linuxbrew/Cellar/libpthread-stubs/0.3/COPYING
/home/linuxbrew/.linuxbrew/Cellar/libpthread-stubs/0.3/README
/home/linuxbrew/.linuxbrew/Cellar/libpthread-stubs/0.3/INSTALL_RECEIPT.json
```

**Comment by bw-yuhogg** [comment]
> libpthread-stubs is just a plug, no?

Yes, but theoretically something could have been compiled differently as a result.

**Comment by maxim-belkin** [comment]
> > libpthread-stubs is just a plug, no?
> 
> Yes, but theoretically something could have been compiled differently as a result.

Not sure how this is possible... 🤔

**Comment by bw-yuhogg** [comment]
Hmm, I think you're right. I probably misread this section from the `libpthread-stubs`README.

```
Design
------

On platforms where the lightweight pthread symbols are provided by the runtime,
the .pc files provides empty Cflags/Libs flags.

Currently the following platforms fit the above category:
 - GNU/Linux - GCC/Clang/GLibC/Musl
...
```

**Comment by bw-yuhogg** [comment]
Revision bumps removed and re-pushed.

**Comment by maxim-belkin** [comment]
how on Earth does this fail?

**Comment by maxim-belkin** [comment]
```
==> Pouring libglvnd-07262016.x86_64_linux.bottle.tar.gz
tar xzf /home/ubuntu/.cache/Homebrew/libglvnd-07262016.x86_64_linux.bottle.tar.gz
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libEGL.so.1.0.0
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libGL.so.1.0.0
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libGLESv1_CM.so.1.0.0
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libGLESv2.so.2.0.0
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libGLX.so.0.0.0
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libGLdispatch.so.0.0.0
/home/linuxbrew/.linuxbrew/opt/patchelf/bin/patchelf --set-rpath /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib:/home/linuxbrew/.linuxbrew/lib:/home/linuxbrew/.linuxbrew/opt/bigreqsproto/lib:/home/linuxbrew/.linuxbrew/opt/compositeproto/lib:/home/linuxbrew/.linuxbrew/opt/damageproto/lib:/home/linuxbrew/.linuxbrew/opt/dmxproto/lib:/home/linuxbrew/.linuxbrew/opt/dri2proto/lib:/home/linuxbrew/.linuxbrew/opt/dri3proto/lib:/home/linuxbrew/.linuxbrew/opt/fixesproto/lib:/home/linuxbrew/.linuxbrew/opt/fontsproto/lib:/home/linuxbrew/.linuxbrew/opt/glproto/lib:/home/linuxbrew/.linuxbrew/opt/inputproto/lib:/home/linuxbrew/.linuxbrew/opt/kbproto/lib:/home/linuxbrew/.linuxbrew/opt/presentproto/lib:/home/linuxbrew/.linuxbrew/opt/randrproto/lib:/home/linuxbrew/.linuxbrew/opt/recordproto/lib:/home/linuxbrew/.linuxbrew/opt/renderproto/lib:/home/linuxbrew/.linuxbrew/opt/resourceproto/lib:/home/linuxbrew/.linuxbrew/opt/scrnsaverproto/lib:/home/linuxbrew/.linuxbrew/opt/videoproto/lib:/home/linuxbrew/.linuxbrew/opt/xcmiscproto/lib:/home/linuxbrew/.linuxbrew/opt/xextproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86bigfontproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86dgaproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86driproto/lib:/home/linuxbrew/.linuxbrew/opt/xf86vidmodeproto/lib:/home/linuxbrew/.linuxbrew/opt/xineramaproto/lib:/home/linuxbrew/.linuxbrew/opt/xproto/lib:/home/linuxbrew/.linuxbrew/opt/libxau/lib:/home/linuxbrew/.linuxbrew/opt/libpthread-stubs/lib:/home/linuxbrew/.linuxbrew/opt/libxdmcp/lib:/home/linuxbrew/.linuxbrew/opt/libxcb/lib:/home/linuxbrew/.linuxbrew/opt/libx11/lib:/home/linuxbrew/.linuxbrew/opt/libxext/lib /home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016/lib/libOpenGL.so.0.0.0
==> Finishing up
ln -s ../Cellar/libglvnd/07262016/include/glvnd glvnd
rm /home/linuxbrew/.linuxbrew/include/glvnd
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /home/linuxbrew/.linuxbrew
Could not symlink lib/libEGL.so
Target /home/linuxbrew/.linuxbrew/lib/libEGL.so
is a symlink belonging to mesa. You can unlink it:
  brew unlink mesa

To force the link and overwrite all conflicting files:
  brew link --overwrite libglvnd

To list all files that would be deleted:
  brew link --overwrite --dry-run libglvnd

Possible conflicting files are:
/home/linuxbrew/.linuxbrew/lib/libEGL.so -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libEGL.so
/home/linuxbrew/.linuxbrew/lib/libEGL.so.1 -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libEGL.so.1
/home/linuxbrew/.linuxbrew/lib/libEGL.so.1.0.0 -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libEGL.so.1.0.0
/home/linuxbrew/.linuxbrew/lib/libGL.so -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGL.so
/home/linuxbrew/.linuxbrew/lib/libGL.so.1 -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGL.so.1
/home/linuxbrew/.linuxbrew/lib/libGLESv1_CM.so -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGLESv1_CM.so
/home/linuxbrew/.linuxbrew/lib/libGLESv1_CM.so.1 -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGLESv1_CM.so.1
/home/linuxbrew/.linuxbrew/lib/libGLESv2.so -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGLESv2.so
/home/linuxbrew/.linuxbrew/lib/libGLESv2.so.2 -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGLESv2.so.2
/home/linuxbrew/.linuxbrew/lib/libGLESv2.so.2.0.0 -> /home/linuxbrew/.linuxbrew/Cellar/mesa/17.1.6/lib/libGLESv2.so.2.0.0
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/libglvnd/07262016: 28 files, 2.2MB
==> FAILED
```

**Comment by bw-yuhogg** [comment]
Closing. Please feel free to use any of this work for a new PR.

**Pull request closed without merging**
