### PR TITLE
libdrm: update to version 2.4.82

### PR DESCRIPTION
**Pull request by maxim-belkin**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
don't expect any problems here

**Comment by bw-yuhogg** [comment]
Travis timed out but was otherwise successful. Circle passed.

**Comment by bw-yuhogg** [comment]
Thanks @maxim-belkin!

**Comment by maxim-belkin** [comment]
No problem, but what about the bottle...?

**Comment by maxim-belkin** [comment]
Oops! Did not see https://github.com/Linuxbrew/homebrew-xorg/commit/e42e5314d444d32b730a93a6e4f8d610c85d585a!

**Pull request closed without merging**
