### PR TITLE
mesa: update patch url

### LINKED ISSUE #228: mesa patch url is dead
(https://travis-ci.org/Homebrew/homebrew-science/builds/183248114)

url can be updated to
http://www.linuxfromscratch.org/patches/downloads/mesa/mesa-12.0.1-add_xdemos-1.patch

### PR DESCRIPTION
**Pull request by rwhogg**
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [ ] Have you included a log of the failed build without your patch using `brew gist-logs <formula>`?
- [ ] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

Fixes #228 (sorry @ilovezfs for not getting to this until now - it's been a busy week).

@maxim-belkin, I'm going to merge this even though I'm expecting CI to fail. homebrew-xorg and Circle haven't been getting along recently, and I have to try and figure out what's wrong with it this weekend. Nevertheless, I'm comfortable merging this because the patch URL doesn't 404 anymore (per `brew fetch` on this branch).

### CODE REVIEW

**Comment by ilovezfs** [comment]
@rwhogg that's OK. Mind checking if siril (see https://github.com/Homebrew/homebrew-science/pull/4708) builds now on Linux if you add linuxbrew/xorg/xorg and linuxbrew/xorg/mesa deps?

**Comment by bw-yuhogg** [comment]
We've been having trouble with both `llvm` and `mesa` on Linuxbrew recently, so I'm not sure if I'll be able to actually get all the needed dependencies to build on my machine.

If they build correctly for me, I'm happy to try.

**Comment by bw-yuhogg** [comment]
I got `llvm` and `mesa` to build, but not `opencv`. I don't have the time to debug the build for that at the moment, so I have to pass on testing `siril` for now.

**Comment by ilovezfs** [comment]
thanks for looking into it

**Pull request merged**
