### PR TITLE
xorg: Depend on libpthread-stubs

### PR DESCRIPTION
**Pull request by iMichka**

### CODE REVIEW

**Comment by maxim-belkin** [comment]
I don't think revision bump is necessary.

**Review by sjackman — APPROVED** [review]

**Comment by iMichka** [comment]
```
==> brew config
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
ORIGIN: https://github.com/Linuxbrew/brew.git
HEAD: dfc4c38491e5201f7191cfc87c70a76a86ca805c
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: b86d95e2d73b69dd5a0e5529aa95892c83e7d058
Core tap last commit: 16 minutes ago
```

**Comment by iMichka** [comment]
Merged. I think there is an update missing somewhere, because it got the wrong brew version in brew config.

**Comment by sjackman** [comment]
I think `brew` repo has to be unshallowed to report correctly the version in
```
HOMEBREW_VERSION: >=1.4.0 (shallow or no git repository)
```

**Pull request closed without merging**
