### PR TITLE
Mass trivial style fix

### PR DESCRIPTION
**Pull request by rwhogg**
Ah, the beauty of `codemod`

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Could you please also fix warnings like `The URL <blah> could use HTTPS rather than HTTP`?
Also, did you plan to fix whitespaces before `=>`?

**Comment by maxim-belkin** [comment]
Nevermind (found #303)

**Review by maxim-belkin — APPROVED** [review]

**Comment by maxim-belkin** [comment]
Could you please add a description of the change when you commit?

**Comment by bw-yuhogg** [comment]
> Also, did you plan to fix whitespaces before =>?

Yes, but I was planning to do this one step at a time.

> Could you please add a description of the change when you commit?

Yeah, described the change more clearly when I merged, thanks for the suggestion.

**Pull request merged**
