### PR TITLE
wayland: revision for libffi

### PR DESCRIPTION
**Pull request by iMichka**
# Contributing to homebrew-xorg:

_You can erase any parts of this template not applicable to your Pull Request._

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [ ] Have you included a log of the failed build without your patch using `brew gist-logs <formula>`?
- [ ] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [ ] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by maxim-belkin** [comment]
rebased and force-pushed

**Comment by maxim-belkin** [comment]
There is no tag in LinuxbrewTestBot https://github.com/LinuxbrewTestBot/homebrew-xorg/releases

**Comment by iMichka** [comment]
I merged this with:
```sh
brew pr-pull --tap=linuxbrew/xorg --bintray-org=linuxbrew --workflow=test_pull_requests.yml 641
```

**Comment by maxim-belkin** [comment]
Thank you, Michka!

**Pull request closed without merging**
