### PR TITLE
Fixing the url for xcb-proto patches.

### PR DESCRIPTION
**Pull request by marlukcz**
Fixing the url for xcb-proto patches.

### CODE REVIEW

**Comment by marlukcz** [comment]
Any idea why the build failed ?

**Comment by maxim-belkin** [comment]
Travis failed to install `gcc-5`.
Would you mind copying the patch to `/Patches` directory instead of just pointing to the new location?
Also, please add a comment right before the patch url where to find it
```ruby
patch :p1 do
  # March 16, 2018
  # http://www.linuxfromscratch.org/patches/blfs/8.2/xcb-proto-1.12-python3-1.patch
  url "https://github.com/Linuxbrew/homebrew-xorg/master/Patches/xcb-proto-1.12-python3-1.patch"
end
```

**Comment by marlukcz** [comment]
Yep, it won't build successfully until merged. Should I create a separate pull request for adding files and for changing URL's ? Original URL's are invalid as well ...

**Comment by maxim-belkin** [comment]
Nope, no need to. It's good enough! thank you

**Comment by maxim-belkin** [comment]
Thank you @marlukcz!

**Pull request closed without merging**
