### PR TITLE
libglvnd 1.3.1

### PR DESCRIPTION
**Pull request by rwhogg**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by maxim-belkin** [comment]
Thanks for the PR, Bob. Currently the plan is to merge linuxbrew/xorg into linuxbrew/core (see #628) and I'd like to postpone updating any packages until that step is complete.
I'd appreciate any help with the aforementioned issue -- basically, formulae have to pass `brew audit --new-formula`.

**Comment by bw-yuhogg** [comment]
Ah, makes sense.

No commitments, I've been super busy lately but I'll keep the current priorities in mind and I'll hold off on submitting any more formula updates to this tap for now.

**Comment by bw-yuhogg** [comment]
@maxim-belkin should we make an exception for new versions that allow us to get rid of patches? Eg. libgudev has a new version that would allow us to drop the patch (https://github.com/GNOME/libgudev/commit/bf8664a028d8cbc55f9dbc65fef926e2119b9579 , https://github.com/GNOME/libgudev/compare/232...233 )

I've got a branch that updates libgudev at https://github.com/rwhogg/homebrew-xorg/tree/libgudev-233

**Comment by maxim-belkin** [comment]
Sure, let's do that. Let me first cherry-pick some commits from #637 to fix audit issues...

**Comment by maxim-belkin** [comment]
done! Feel free to submit your PR.

**Comment by bw-yuhogg** [comment]
Temporarily closing. I'll resurrect it in the future if appropriate.

**Pull request closed without merging**
