### PR TITLE
Xorg server

### PR DESCRIPTION
**Pull request by maxim-belkin**
## Contributing to homebrew-xorg:

_You can erase any parts of this template not applicable to your Pull Request._
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [x] Does your submission pass
  `brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

---

xorg-server: new formula.
tests are disabled because xtest is failing

### CODE REVIEW

**Comment by maxim-belkin** [comment]
weird error message on Travis:

``` ruby
==> Fetching xorg-fonts from linuxbrew/xorg
==> Downloading https://gist.githubusercontent.com/maxim-belkin/6fd6422cbe4da6ea0555d7a8d9911bc2/raw/c38d109967382d35f9f8a89542c18abbfb27cf88/README.md
Downloaded to: /home/linuxbrew/.cache/Homebrew/xorg-fonts-20160522.md
SHA256: 3baf64afb29129ea9f74d5ae5a223b072d0911d96283f834e37d8f65d751c5d7
==> Retrying download
==> Downloading https://gist.githubusercontent.com/maxim-belkin/6fd6422cbe4da6ea0555d7a8d9911bc2/raw/c38d109967382d35f9f8a89542c18abbfb27cf88/README.md
Warning: Formula reports different SHA256: f93f89000f05e50c9b27a00504815c7e1f2431d13ab838e60d3874bf356b8e1b
Downloaded to: /home/linuxbrew/.cache/Homebrew/xorg-fonts-20160522.md
SHA256: 3baf64afb29129ea9f74d5ae5a223b072d0911d96283f834e37d8f65d751c5d7
```

**Comment by maxim-belkin** [comment]
rebased PR on top of the fix to `xorg-fonts` package. Restarting the build.

**Comment by maxim-belkin** [comment]
rebased the PR on top of several fixes (including the ones for font-util (+bottle) and mkfontscale)

**Comment by maxim-belkin** [comment]
Failure is caused by `valgrind`

**Comment by maxim-belkin** [comment]
```
==> ./configure --prefix=/home/linuxbrew/.linuxbrew/Cellar/xorg-server/1.19.3 --sysconfdir=/home/linuxbrew/.linuxbrew/etc --localstatedir=/home/linuxbrew/.linuxbrew/var --disable-dependency-tracking --disable-silent-rules --enable-suid-wrapper --disable-systemd-logind --enable-glamor --enable-xwayland
.
Last 150 lines from /home/ubuntu/.cache/Homebrew/Logs/xorg-server/01.configure:
checking for sys/mkdev.h... no
checking sys/utsname.h usability... yes
checking sys/utsname.h presence... yes
checking for sys/utsname.h... yes
checking for an ANSI C-conforming const... yes
checking for typeof syntax and keyword spelling... typeof
checking whether byte ordering is bigendian... no
checking size of unsigned long... 8
checking for pid_t... yes
checking byteswap.h usability... yes
checking byteswap.h presence... yes
checking for byteswap.h... yes
checking sys/endian.h usability... no
checking sys/endian.h presence... no
checking for sys/endian.h... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking for backtrace... yes
checking for ffs... yes
checking for geteuid... yes
checking for getuid... yes
checking for issetugid... no
checking for getresuid... yes
checking for getdtablesize... yes
checking for getifaddrs... yes
checking for getpeereid... no
checking for getpeerucred... no
checking for getprogname... no
checking for getzoneid... no
checking for mmap... yes
checking for posix_fallocate... yes
checking for seteuid... yes
checking for shmctl64... no
checking for strncasecmp... yes
checking for vasprintf... yes
checking for vsnprintf... yes
checking for walkcontext... no
checking for setitimer... yes
checking for poll... yes
checking for epoll_create1... yes
checking for reallocarray... no
checking for strcasecmp... yes
checking for strcasestr... yes
checking for strlcat... no
checking for strlcpy... no
checking for strndup... yes
checking for timingsafe_memcmp... no
checking for arc4random_buf in -lbsd... no
checking for arc4random_buf... no
checking whether program_invocation_short_name is declared... yes
checking for SO_PEERCRED in sys/socket.h... yes
checking for sqrt in -lm... yes
checking for cbrt... yes
checking ndbm.h usability... no
checking ndbm.h presence... no
checking for ndbm.h... no
checking dbm.h usability... no
checking dbm.h presence... no
checking for dbm.h... no
checking rpcsvc/dbm.h usability... no
checking rpcsvc/dbm.h presence... no
checking for rpcsvc/dbm.h... no
checking linux/agpgart.h usability... yes
checking linux/agpgart.h presence... yes
checking for linux/agpgart.h... yes
checking sys/agpio.h usability... no
checking sys/agpio.h presence... no
checking for sys/agpio.h... no
checking sys/agpgart.h usability... no
checking sys/agpgart.h presence... no
checking for sys/agpgart.h... no
checking linux/fb.h usability... yes
checking linux/fb.h presence... yes
checking for linux/fb.h... yes
checking for sys/linker.h... no
checking for SYSV IPC... yes
checking machine/apmvar.h usability... no
checking machine/apmvar.h presence... no
checking for machine/apmvar.h... no
checking execinfo.h usability... yes
checking execinfo.h presence... yes
checking for execinfo.h... yes
checking for backtrace in -lc... yes
checking for fallback input driver... libinput
checking for root directory for font files... /home/linuxbrew/.linuxbrew/Cellar/font-util/1.3.1/share/fonts/X11
checking for directory for misc files... ${FONTROOTDIR}/misc
checking for directory for OTF files... ${FONTROOTDIR}/OTF
checking for directory for TTF files... ${FONTROOTDIR}/TTF
checking for directory for Type1 files... ${FONTROOTDIR}/Type1
checking for directory for 75dpi files... ${FONTROOTDIR}/75dpi
checking for directory for 100dpi files... ${FONTROOTDIR}/100dpi
checking for default font path... ${FONTROOTDIR}/misc/,${FONTROOTDIR}/TTF/,${FONTROOTDIR}/OTF/,${FONTROOTDIR}/Type1/,${FONTROOTDIR}/100dpi/,${FONTROOTDIR}/75dpi/
checking to see if we can install the Xorg server as root... no
checking if Xtrans should support UNIX socket connections... yes
checking if Xtrans should support TCP socket connections... yes
checking for library containing socket... none required
checking for library containing gethostbyname... none required
checking for getaddrinfo... yes
checking if IPv6 support should be built... yes
checking for struct sockaddr_in.sin_len... no
checking for socklen_t... yes
checking for struct msghdr.msg_control... yes
checking if Xtrans should support os-specific local connections... no
checking for authdes_seccreate... no
checking for authdes_create... yes
checking for library containing getsecretkey... none required
checking if Secure RPC authentication ("SUN-DES-1") should be supported... yes
checking for PIXMAN... yes
checking whether PTHREAD_MUTEX_RECURSIVE is declared... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for pthread_setname_np(const char*)... no
checking for pthread_setname_np(pthread_t, const char*)... yes
checking for SYSTEMD_DAEMON... yes
checking for UDEV... yes
checking for udev_monitor_filter_add_match_tag... yes
checking for udev_enumerate_add_match_tag... yes
checking for DBUS... no
checking for HAL... no
checking for glibc...... yes
checking for clock_gettime... yes
checking for a useful monotonic clock ...... yes
checking whether to track client ids... yes
checking for DRI2PROTO... yes
Checking temp dir /run/shm
checking for DRI3PROTO... yes
checking for sigaction... yes
checking for XSHMFENCE... no
configure: DRI3 disabled because xshmfence not found.
checking for LIBDRM... yes
checking for XLIB... yes
checking for GL... no
configure: error: Package requirements (glproto >= 1.4.17 gl >= 9.2.0) were not met:

Package 'xdamage', required by 'gl', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GL_CFLAGS
and GL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by maxim-belkin** [comment]
```
==> brew audit linuxbrew/xorg/xorg-server --online --new-formula
==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Successfully installed ast-2.3.0
Successfully installed parser-2.4.0.0
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.3.0
Successfully installed parallel-1.12.0
Successfully installed rubocop-0.49.1
8 gems installed
Error: 2 problems in 1 formula
linuxbrew/xorg/xorg-server:
  * The URL http://www.x.org/ could use HTTPS rather than HTTP
  * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
==> FAILED
==> brew bottle --verbose --json linuxbrew/xorg/xorg-server
Error: Formula not installed or up-to-date: linuxbrew/xorg/xorg-server
```

**Comment by maxim-belkin** [comment]
```
==> brew audit linuxbrew/xorg/xorg-server --online --new-formula
==> Installing or updating 'rubocop' gem
Building native extensions.  This could take a while...
Successfully installed rainbow-2.2.2
Successfully installed ast-2.3.0
Successfully installed parser-2.4.0.0
Successfully installed powerpack-0.1.1
Successfully installed ruby-progressbar-1.8.1
Successfully installed unicode-display_width-1.3.0
Successfully installed parallel-1.12.0
Successfully installed rubocop-0.49.1
8 gems installed
Error: 1 problem in 1 formula
linuxbrew/xorg/xorg-server:
  * New formulae should not require patches to build. Patches should be submitted and accepted upstream first.
==> FAILED
==> brew bottle --verbose --json linuxbrew/xorg/xorg-server
Error: Formula not installed or up-to-date: linuxbrew/xorg/xorg-server
==> FAILED
==> brew linkage linuxbrew/xorg/xorg-server
Error: No such keg: /home/linuxbrew/.linuxbrew/Cellar/xorg-server
==> FAILED
==> brew linkage --test linuxbrew/xorg/xorg-server
Error: No such keg: /home/linuxbrew/.linuxbrew/Cellar/xorg-server
==> FAILED
==> brew test linuxbrew/xorg/xorg-server --verbose
Error: Testing requires the latest version of linuxbrew/xorg/xorg-server
==> FAILED
```

**Comment by maxim-belkin** [comment]
Very logical error:
```
==> Installing linuxbrew/xorg/xorg-server dependency: linuxbrew/xorg/wayland-protocols
==> Downloading https://linuxbrew.bintray.com/bottles-xorg/wayland-protocols-1.7.x86_64_linux.bottle.tar.gz
Already downloaded: /home/ubuntu/.cache/Homebrew/wayland-protocols-1.7.x86_64_linux.bottle.tar.gz
==> Verifying wayland-protocols-1.7.x86_64_linux.bottle.tar.gz checksum
==> Pouring wayland-protocols-1.7.x86_64_linux.bottle.tar.gz
tar xzf /home/ubuntu/.cache/Homebrew/wayland-protocols-1.7.x86_64_linux.bottle.tar.gz
==> Finishing up
ln -s ../../Cellar/wayland-protocols/1.7/share/pkgconfig/wayland-protocols.pc wayland-protocols.pc
ln -s ../Cellar/wayland-protocols/1.7/share/wayland-protocols wayland-protocols
==> Summary
/home/linuxbrew/.linuxbrew/Cellar/wayland-protocols/1.7: 20 files, 273.3KB
==> FAILED
```

**Comment by maxim-belkin** [comment]
Circle:
```
==> brew linkage linuxbrew/xorg/xorg-server
System libraries:
  /lib/x86_64-linux-gnu/libc.so.6
  /lib/x86_64-linux-gnu/libdl.so.2
  /lib/x86_64-linux-gnu/libm.so.6
  /lib/x86_64-linux-gnu/libpthread.so.0
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libbsd.so.0 (libbsd)
  /home/linuxbrew/.linuxbrew/lib/libepoxy.so.0 (libepoxy)
  /home/linuxbrew/.linuxbrew/opt/libunwind/lib/libunwind.so.8 (libunwind)
  /home/linuxbrew/.linuxbrew/lib/libdrm.so.2 (linuxbrew/xorg/libdrm)
  /home/linuxbrew/.linuxbrew/lib/libpciaccess.so.0 (linuxbrew/xorg/libpciaccess)
  /home/linuxbrew/.linuxbrew/lib/libsha1.so.0 (linuxbrew/xorg/libsha1)
  /home/linuxbrew/.linuxbrew/lib/libX11.so.6 (linuxbrew/xorg/libx11)
  /home/linuxbrew/.linuxbrew/lib/libXau.so.6 (linuxbrew/xorg/libxau)
  /home/linuxbrew/.linuxbrew/lib/libXdmcp.so.6 (linuxbrew/xorg/libxdmcp)
  /home/linuxbrew/.linuxbrew/lib/libXext.so.6 (linuxbrew/xorg/libxext)
  /home/linuxbrew/.linuxbrew/lib/libXfont2.so.2 (linuxbrew/xorg/libxfont2)
  /home/linuxbrew/.linuxbrew/lib/libxshmfence.so.1 (linuxbrew/xorg/libxshmfence)
  /home/linuxbrew/.linuxbrew/lib/libEGL.so.1 (linuxbrew/xorg/mesa)
  /home/linuxbrew/.linuxbrew/lib/libGL.so.1 (linuxbrew/xorg/mesa)
  /home/linuxbrew/.linuxbrew/lib/libgbm.so.1 (linuxbrew/xorg/mesa)
  /home/linuxbrew/.linuxbrew/lib/libwayland-client.so.0 (linuxbrew/xorg/wayland)
  /home/linuxbrew/.linuxbrew/lib/libpixman-1.so.0 (pixman)
  /home/linuxbrew/.linuxbrew/lib/libsystemd.so.0 (systemd)
  /home/linuxbrew/.linuxbrew/lib/libudev.so.1 (systemd)
Possible undeclared dependencies:
  libbsd
  linuxbrew/xorg/libdrm
  linuxbrew/xorg/libpciaccess
  linuxbrew/xorg/libsha1
  linuxbrew/xorg/libx11
  linuxbrew/xorg/libxau
  linuxbrew/xorg/libxdmcp
  linuxbrew/xorg/libxext
  systemd
```

Local installation:
```
$ brew linkage xorg-server
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libc.so.6 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libdl.so.2 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libm.so.6 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libbsd.so.0 (libbsd)
  /home/linuxbrew/.linuxbrew/lib/libepoxy.so.0 (libepoxy)
  /home/linuxbrew/.linuxbrew/opt/libunwind/lib/libunwind.so.8 (libunwind)
  /home/linuxbrew/.linuxbrew/lib/libdrm.so.2 (linuxbrew/xorg/libdrm)
  /home/linuxbrew/.linuxbrew/lib/libpciaccess.so.0 (linuxbrew/xorg/libpciaccess)
  /home/linuxbrew/.linuxbrew/lib/libsha1.so.0 (linuxbrew/xorg/libsha1)
  /home/linuxbrew/.linuxbrew/lib/libX11.so.6 (linuxbrew/xorg/libx11)
  /home/linuxbrew/.linuxbrew/lib/libXau.so.6 (linuxbrew/xorg/libxau)
  /home/linuxbrew/.linuxbrew/lib/libXdmcp.so.6 (linuxbrew/xorg/libxdmcp)
  /home/linuxbrew/.linuxbrew/lib/libXext.so.6 (linuxbrew/xorg/libxext)
  /home/linuxbrew/.linuxbrew/lib/libXfont2.so.2 (linuxbrew/xorg/libxfont2)
  /home/linuxbrew/.linuxbrew/lib/libxshmfence.so.1 (linuxbrew/xorg/libxshmfence)
  /home/linuxbrew/.linuxbrew/lib/libEGL.so.1 (linuxbrew/xorg/mesa)
  /home/linuxbrew/.linuxbrew/lib/libGL.so.1 (linuxbrew/xorg/mesa)
  /home/linuxbrew/.linuxbrew/lib/libgbm.so.1 (linuxbrew/xorg/mesa)
  /home/linuxbrew/.linuxbrew/lib/libwayland-client.so.0 (linuxbrew/xorg/wayland)
  /home/linuxbrew/.linuxbrew/lib/libpixman-1.so.0 (pixman)
  /home/linuxbrew/.linuxbrew/lib/libsystemd.so.0 (systemd)
  /home/linuxbrew/.linuxbrew/lib/libudev.so.1 (systemd)
Missing libraries:
  libgcrypt.so.11
Possible undeclared dependencies:
  libbsd
  linuxbrew/xorg/libdrm
  linuxbrew/xorg/libpciaccess
  linuxbrew/xorg/libsha1
  linuxbrew/xorg/libx11
  linuxbrew/xorg/libxau
  linuxbrew/xorg/libxdmcp
  linuxbrew/xorg/libxext
  systemd

$ brew linkage --reverse xorg-server
... snip ...
libgcrypt.so.11
  bin/Xfbdev
  bin/Xnest
  bin/Xvfb
  bin/Xwayland
  libexec/Xorg
```

**Comment by maxim-belkin** [comment]
```
/home/linuxbrew/.linuxbrew/bin/ld: warning: libgcrypt.so.11, needed by /home/linuxbrew/.linuxbrew/Cellar/systemd/221/lib/libsystemd.so, may conflict with libgcrypt.so.20
```
should we recompile `systemd` with Linuxbrew's `libgcrypt`?

And, related in general but different (@sjackman):
```
$ brew linkage systemd
Homebrew libraries:
  /home/linuxbrew/.linuxbrew/lib/libc.so.6 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libcrypt.so.1 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libdl.so.2 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libm.so.6 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libresolv.so.2 (glibc)
  /home/linuxbrew/.linuxbrew/lib/librt.so.1 (glibc)
  /home/linuxbrew/.linuxbrew/lib/libcap.so.2 (libcap)
  /home/linuxbrew/.linuxbrew/lib/libblkid.so.1 (util-linux)
  /home/linuxbrew/.linuxbrew/lib/libmount.so.1 (util-linux)
  /home/linuxbrew/.linuxbrew/lib/liblzma.so.5 (xz)
Missing libraries:
  libgcrypt.so.11
Possible undeclared dependencies:
  xz
```

**Comment by sjackman** [comment]
> should we recompile systemd with Linuxbrew's libgcrypt?

Looks like yes. `systemd` is being difficult to compile at the moment.
See https://github.com/Linuxbrew/homebrew-core/pull/1946 and https://github.com/Linuxbrew/homebrew-core/pull/2795

**Pull request closed without merging**
