### PR TITLE
libvdpau-va-gl: depends on glib for Linuxbrew

### PR DESCRIPTION
**Pull request by rwhogg**
I'm expecting this to fail; I just want to see *how* it fails.

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
From Travis (https://travis-ci.org/Linuxbrew/homebrew-xorg/builds/220167867#L6616-L6617):

```
-- Checking for module 'glib-2.0'
--   Package 'libpcre', required by 'glib-2.0', not found
```

Depends on `glib`.

**Comment by bw-yuhogg** [comment]
Now:

```
Checking for module 'libva-x11'
--   No package 'libva-x11' found
```

**Comment by maxim-belkin** [comment]
> maxim-belkin self-requested a review just now 

🤣

**Comment by maxim-belkin** [comment]
@rwhogg these dependencies are required by `libvdpau-va-gl`, not `libvdpau`.

**Comment by bw-yuhogg** [comment]
> @rwhogg these dependencies are required by libvdpau-va-gl, not libvdpau.

Whoops... thanks for the catch!

**Comment by maxim-belkin** [comment]
oh, formula is correct, it's title that's not correct. sorry))

**Comment by bw-yuhogg** [comment]
Blocked by #291

**Comment by maxim-belkin** [comment]
@rwhogg see line 12 :)
I'll work on this formula. I don't think it is blocked by #291.

**Pull request closed without merging**
