### PR TITLE
xmessage: Add test

### PR DESCRIPTION
**Pull request by rwhogg**
# Contributing to homebrew-xorg:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [x] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

Not entirely sure this is going to work on CI, but guess we'll find out.

### CODE REVIEW

**Comment by bw-yuhogg** [comment]
Hmm, apparently `brew style linuxbrew/xorg` failed:

```

== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Livecheckables/intel-media-driver.rb ==
C:  4: 78: Redundant escape inside regexp literal
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Livecheckables/libva-intel-driver.rb ==
C:  4: 70: Redundant escape inside regexp literal
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Livecheckables/libva-internal.rb ==
C:  4: 57: Redundant escape inside regexp literal
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Livecheckables/libva.rb ==
C:  4: 57: Redundant escape inside regexp literal
== /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg/Livecheckables/libvdpau-va-gl.rb ==
C:  4: 68: Redundant escape inside regexp literal
```

Since I was the last person to touch all of those files, I'll take a look at them later this week (but obviously anyone is welcome to fix them themselves if they want to)

**Comment by bw-yuhogg** [comment]
It was a trivial fix. Submitted separately as #654

**Review by maxim-belkin — APPROVED** [review]

**Comment by bw-yuhogg** [comment]
```
Testing linuxbrew/xorg/xmessage
==> xmessage -timeout 1 Hello Homebrew
Error: Can't open display: 
Error: linuxbrew/xorg/xmessage: failed
```

Yeah, I was wondering if it was gonna do that... This might require some additional thought as to the best way to handle tests that require an X server.

**Comment by maxim-belkin** [comment]
Looks like fake X11 is finally working.
I'm going to squash my commits into one.

**Comment by maxim-belkin** [comment]
@sjackman , have a look at this magic: we're testing an X11 app here 😎

**Comment by maxim-belkin** [comment]
@rwhogg , I'm going to stop tinkering with `xvfb-run` and merge this "as is"
I wanted to use `xvfb-run -a brew test-bot...` because this is a one-line change compared to what I had to do here... but it doesn't work for some reason.

**Comment by sjackman** [comment]
> have a look at this magic: we're testing an X11 app here 😎

Woohoo! That's awesome!

**Pull request merged**
