### PR TITLE
mesa: failed with llvm@6

### PR DESCRIPTION
**Pull request by Gwang-Jin**
I changed `llvm@6` into `llvm@4`.
`--enable-gallium-llvm` option was deprecated and needed to be changed to `--enable-llvm.`

# Contributing to homebrew-xorg:

_You can erase any parts of this template not applicable to your Pull Request._

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Linuxbrew/homebrew-xorg/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Linuxbrew/homebrew-xorg/pulls) for the same update/change?
- [x] Have you included a log of the failed build without your patch using `brew gist-logs <formula>`?
- [x] Does your submission pass
`brew audit --strict <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

### CODE REVIEW

**Comment by dpo** [comment]
CircleCI says
```
checking for x11 xext xdamage >= 1.1 xfixes x11-xcb xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8... no
configure: error: Package requirements (x11 xext xdamage >= 1.1 xfixes x11-xcb xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8) were not met:

Package 'kbproto', required by 'x11', not found
```

**Comment by nir-krakauer** [comment]
These modifications to `mesa.rb` enable me to install it, on Ubuntu.

**Comment by Gwang-Jin** [comment]
@dpo I've added `depends_on "linuxbrew/xorg/kbproto"`. And should I include `xextproto` and `xf86vidmodeproto`?

**Comment by dpo** [comment]
Here's the next error message:
```
checking for x11 xext xdamage >= 1.1 xfixes x11-xcb xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8... no
configure: error: Package requirements (x11 xext xdamage >= 1.1 xfixes x11-xcb xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8) were not met:

Package 'xextproto', required by 'xext', not found
```
Looks like we're discovering them one by one.

**Comment by maxim-belkin** [comment]
Hey, @Gwang-Jin and @dpo. Our planned course of action is to remove llvm dependency and make it an optional one. I'll look into mesa issues today

**Comment by Gwang-Jin** [comment]
@dpo I added other dependencies.

**Comment by Gwang-Jin** [comment]
@maxim-belkin Ok. It seems to be possible if we use
`--with-dri-drivers= --with-gallium-drivers=r600 --disable-gallium-llvm`

[https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/opengl-vulkan-mesa-gallium3d/38705-is-llvm-strictly-required-for-building-mesa-gallium-radeon](https://www.phoronix.com/forums/forum/linux-graphics-x-org-drivers/opengl-vulkan-mesa-gallium3d/38705-is-llvm-strictly-required-for-building-mesa-gallium-radeon)


But it is need to be checked.

**Comment by Gwang-Jin** [comment]
@dpo I have a question: Is it more precise
````
   depends_on "linuxbrew/xorg/dri2proto"
   depends_on "linuxbrew/xorg/glproto"
   depends_on "linuxbrew/xorg/kbproto" if build.with? "libva"
   depends_on "linuxbrew/xorg/xextproto" if build.with? "libva"
   depends_on "linuxbrew/xorg/xf86vidmodeproto" if build.with? "libva"
   depends_on "linuxbrew/xorg/fixesproto" if build.with? "libva"
````
?

`kbproto`, `xextproto`, `xf86vidmodeproto` ,and `fixesproto` weren't need to be build mesa without `libva.`

Ok. I will try to check them using ci/circleci.

**Comment by dpo** [comment]
We're back to
```
checking for x11 xext xdamage >= 1.1 xfixes x11-xcb xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8... no
configure: error: Package requirements (x11 xext xdamage >= 1.1 xfixes x11-xcb xcb xcb-glx >= 1.8.1 xcb-dri2 >= 1.8) were not met:

Package 'kbproto', required by 'x11', not found
```
It looks like `kbproto` is needed, even without `libva`.

**Comment by Gwang-Jin** [comment]
Ok. I removed `"if build.with? "libva""`. It would pass ci/circlei.

**Comment by dpo** [comment]
Looks good! Many thanks! Would you mind making `llvm` support optional, as suggested by @maxim-belkin?

**Comment by Gwang-Jin** [comment]
Regarding `--without-llvm`, only `r600` driver can be used. It would be possible. And I would like to add an option `--with-gallium-osmesa` (Disable the older classic OSMesa in favor of the newer gallium OSMesa). But these options are conflict. `--with-gallium-osmesa` requires `--with-gallium-drivers=swrast,swr`. So I want to finish this PR here and will try another PR. Thanks.

**Comment by dpo** [comment]
@maxim-belkin Is there something holding this up?

**Comment by maxim-belkin** [comment]
Thanks, @Gwang-Jin and @dpo!
I've tested this locally and mesa builds fine with it. As I mentioned before, the plan is to make llvm dependency optional but your solution is good until we do that.

**Comment by dpo** [comment]
Great! Thank you.

**Pull request closed without merging**
